    - name: Install dependencies
      apt: name={{ item }} state=present
      with_items:
       - python
       - python3
       - python-setuptools
       - python-dev
       - build-essential
       - python-pip
       - python3-pip
       - python-mysqldb
       - git